services:
  - type: web
    name: budgetbuddy
    env: node
    region: oregon
    buildCommand: npm install && cd frontend && npm install && npm run build && cd ..
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: NODE_ENV
        value: production
